### ISSUE TITLE
Case-sensitive lookups of variable names somewhere in jsviz/vizgpm

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/iventure#38]
interactive_pairplot fails to produce a plot, and instead yields `Error: unknown column ...`, if the query fed to it yields a column name that differs in case from the corresponding column name in the population.

**Comment by fsaad** [comment]
@riastradh-probcomp please provide a minimum working example.

**Comment by riastradh-probcomp** [comment]
Kinda rude to ask for feedback and then close the issue without waiting for any!

This should do it:

```
%load_ext jupyter_probcomp.magics
%matplotlib inline
%vizgpm inline
%bayesdb test.bdb
%bql create table t as select * from sqlite_master
%bql create population p for t with schema (guess (*); model Tbl_Name as nominal)
%bql create metamodel m for p with baseline crosscat
%bql .interactive_pairplot --population=p estimate type, tbl_Name from p
```

**Comment by riastradh-probcomp** [comment]
It's possible that won't do it (I don't have a setup I can easily test with the bug at the moment) but if it doesn't, then this should instead:

```
%load_ext jupyter_probcomp.magics
%matplotlib inline
%vizgpm inline
%bayesdb test.bdb
%sql create table t(x, Y)
%sql insert into t values(1,2)
%sql insert into t values(2,4)
%sql insert into t values(3,6)
%bql create population p for t with schema (model x, y as numerical)
%bql create metamodel m for p with baseline crosscat
%bql .interactive_pairplot --population=p estimate * from p
```

**Comment by fsaad** [comment]
> Kinda rude to ask for feedback and then close the issue without waiting for any!

@riastradh-probcomp Closed the issue since it was fixed, please refer to https://github.com/probcomp/iventure/commit/abf56460a69d0771bc6e6e1ceb5211190abe7aeb.

**Comment by riastradh-probcomp** [comment]
OK, sorry, didn't realize that.  (Always helpful to cite the commit that fixes an issue in a comment closing it!)

**Comment by riastradh-probcomp** [comment]
Oh, pfeh.  I am sorry; you _did_ cite the commit automagically and I just didn't read closely enough.
