### ISSUE TITLE
Add a .subsample_rows dot command

### ISSUE THREAD

**Issue by curlette** [probcomp/iventure#60]
Analogous to `.subsample_columns`. For very large csvs, it may be useful to scale down the number of rows immediately (i.e. before analysis).

**Comment by fsaad** [comment]
Why not just use SQL?

**Comment by curlette** [comment]
Good point. I was thinking of it from the usability standpoint of design parallelism, because someone at the workshops expected this to exist because subsample_columns does. I guess the main advantage is not having to create (and optionally drop after sampling) a large (e.g. 100,000+ rows) table in the db.

**Comment by fsaad** [comment]
>  I guess the main advantage is not having to create (and optionally drop after sampling) a large (e.g. 100,000+ rows) table in the db.

I do not think that iventure should aim at creating or automating csv manipulation routines for files on disk; these operations are best specified manually using the python capabilities of iventure and libraries such as pandas.

**Comment by curlette** [comment]
@fsaad 

> Why not just use SQL?

it seems that now that the "proper way" of randomly subsampling rows from a table using SQL (making use of BQL's seeded rand) requires the following two steps:

`%sql CREATE TABLE <t> AS SELECT <cols>, bql_rand() as rand FROM <table> ORDER BY rand LIMIT <lim>`

`%sql CREATE TABLE <t_final> AS SELECT <cols_except_rand> FROM <t>`, where `cols_except_rand` is all columns except `rand` from <cols> in the query above. This step is necessary because there is no way to execute `bql_rand()` on a per row basis and order by it without selecting it (and presumably a user does not want a new `rand` column in their subsampled table).

I am wondering whether it is worth automating those steps with a %bql magic.

**Comment by curlette** [comment]
@fsaad FWIW, I got another question today re: "where is the documentation for `.subsample_rows`?"
