### ISSUE TITLE
In .subsample_columns, in --keep, column names with spaces create an error

### ISSUE THREAD

**Issue by versar** [probcomp/iventure#72]
For example:

`%bql .subsample_columns --seed=8 --keep=Country,"life expectancy at birth" gapminder_t gapminder_t_subsample 30` 

returns:
```
usage: ipykernel_launcher.py [-h] [--keep KEEP] [--seed SEED]
                             table new_table limit
ipykernel_launcher.py: error: argument limit: invalid int value: 'birth"'
```

I tried single quotes, double quotes, double quotes within single quotes, and single quotes within double quotes.

**Comment by fsaad** [comment]
Related https://github.com/probcomp/iventure/issues/58

We need to fix the argument parser, removing the commas convention and permitting varargs for --keep and --drop.
